-- Always target correct PDB and schema
ALTER SESSION SET CONTAINER = FREEPDB1;
ALTER SESSION SET CURRENT_SCHEMA = seed;

-- Make SQL*Plus display readable (students will love this)
SET PAGESIZE 220
SET LINESIZE 200
SET LONG 20000
SET LONGCHUNKSIZE 20000
COLUMN name FORMAT A10
COLUMN address FORMAT A30
COLUMN email FORMAT A25
COLUMN password FORMAT A40

-- Drop table safely (IMPORTANT: the "/" line executes the PL/SQL block)
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE credential PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -942 THEN NULL; ELSE RAISE; END IF;
END;
/

-- Create table
CREATE TABLE credential (
  ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  Name        VARCHAR2(50),
  EID         NUMBER,
  Salary      NUMBER,
  birth       VARCHAR2(20),
  SSN         VARCHAR2(11),
  PhoneNumber VARCHAR2(20),
  Address     VARCHAR2(200),
  Email       VARCHAR2(100),
  NickName    VARCHAR2(50),
  Password    VARCHAR2(200)
);

-- Insert rows 
INSERT INTO credential (Name, EID, Salary, birth, SSN, PhoneNumber, Address, Email, NickName, Password)
VALUES ('Alice', 10000, 20000, '9/20', 10211002, NULL, NULL, NULL, NULL, 'fdbe918bdae83000aa54747fc95fe0470fff4976');

INSERT INTO credential (Name, EID, Salary, birth, SSN, PhoneNumber, Address, Email, NickName, Password)
VALUES ('Boby', 20000, 30000, '4/20', 10213352, NULL, NULL, NULL, NULL, 'b78ed97677c161c1c82c142906674ad15242b2d4');

INSERT INTO credential (Name, EID, Salary, birth, SSN, PhoneNumber, Address, Email, NickName, Password)
VALUES ('Ryan', 30000, 50000, '4/10', 98993524, NULL, NULL, NULL, NULL, 'a3c50276cb120637cca669eb38fb9928b017e9ef');

INSERT INTO credential (Name, EID, Salary, birth, SSN, PhoneNumber, Address, Email, NickName, Password)
VALUES ('Samy', 40000, 90000, '1/11', 32193525, NULL, NULL, NULL, NULL, '995b8b8c183f349b3cab0ae7fccd39133508d2af');

INSERT INTO credential (Name, EID, Salary, birth, SSN, PhoneNumber, Address, Email, NickName, Password)
VALUES ('Ted', 50000, 110000, '11/3', 32111111, NULL, NULL, NULL, NULL, '99343bff28a7bb51cb6f22cb20a618701a2c2f58');

INSERT INTO credential (Name, EID, Salary, birth, SSN, PhoneNumber, Address, Email, NickName, Password)
VALUES ('Admin', 99999, 400000, '3/5', 43254314, NULL, NULL, NULL, NULL, 'a5bdf35a1df4ea895905f6f6618e83951a6effc0');

COMMIT;
